### ISSUE TITLE
Use without docker

### ISSUE THREAD

**Issue by jblac** [codacy/codacy-analysis-cli#176]
How can this be used without docker?    I don't use docker, nor do I plan to use docker,  but I'd still like to run my codacy rules locally (it's really within a VM but it's not a container - which really shouldn't be a requirement.) - what options are available to facilitate that?

**Comment by lolgab** [comment]
Hi @jblac,
Sadly all our tools are built around docker and there is no way you can run them without using Docker :(
I'm closing this as wontfix.

Lorenzo

**Comment by jblac** [comment]
Alright, you strive for mediocrity - got it.   A developer tool that forces an entire container to run is utterly insane and outright retarded.
