### ISSUE TITLE
Are the prerequisites for developing or simply using the tool?

### ISSUE THREAD

**Issue by StingyJack** [codacy/codacy-analysis-cli#265]
Requiring all of the WSL and docker to be setup for windows development seems like a reasonable and not uncommon arrangement, but not so for simply using the tool. Please confirm or clarify which prerequisite set applies to which use case

**Comment by franciscodua** [comment]
Hi @StingyJack 

You can follow this [guide](https://medium.com/@hjrocha/codacy-cli-on-windows-with-two-simple-steps-1bfc62f73d2c) instead.

Regarding the Docker requirement: the CLI's goal is to bring Codacy to users' machines. And we achieve this by running these linters, in the same environment as the one Codacy uses, via Docker containers. So the CLI is launching Docker containers to run these tools, hence the need to have Docker enabled.

Let us know if this worked for you

**Comment by StingyJack** [comment]
I'm familiar with Docker, WSL, etc.  This is what I have to go on from a chat I was having in the codacy website chat app. 

> The results for the PR analysis can be returned on Codacy UI, on GitHub side (by having PR options checked in the repository's settings > Integrations > GitHub) or by using our CLI, the latest one is useful to receive the analyses results locally, which could be useful for you to incorporate in your setup.

So I'm expecting that the CLI just gets something that was already executed and completed, not that it executes anew.   Does this make sense to you? I'm having a little bit of trouble following along with some of this.

**Comment by franciscodua** [comment]
What the CLI does is execute Codacy's linters on your machine or CI. I think the idea behind

> is useful to receive the analyses results locally

is that you can use it to validate your changes before committing them, shortening the feedback loop.

So, if you just want to get feedback on Codacy dashboard, or on your Github PR, for example, you can just use the linters Codacy runs server-side and follow the steps you have there.

If you want to validate your changes locally or even integrate Codacy into your CI (if for example, you want the CI to stop running if the analysis finds results) you should use the CLI.

Did this explanation help? I'll create an issue on our side to improve our documentation and try to make this easier to understand.

**Comment by franciscodua** [comment]
Closing this issue.
If you still have questions related to this re-open it or create a new one.
