### ISSUE TITLE
[CY-3412] Linux Installation

### ISSUE THREAD

**Issue by TheShubhendra** [codacy/codacy-analysis-cli#341]
How to install it on Linux environment of **Termux**

**Comment by josemiguelmelo** [comment]
Hi @TheShubhendra ,

Our codacy-analysis-cli has 2 requirements to run:
- Java 8+
- Docker

From a quick search, it seems Docker is still not supported on **Termux** and, as consequence, I think our CLI is currently not available for this Linux environment.
