### ISSUE TITLE
[CY-3881] Not Compatible with Java 11

### ISSUE THREAD

**Issue by timnolte** [codacy/codacy-analysis-cli#349]
Building the Codacy CLI on Linux doesn't support Java 11. You are using the `UseCGroupMemoryLimitForHeap` feature which has been removed in JDK 11 and replaced with `UseContainerSupport`. The `UseCGroupMemoryLimitForHeap` was actually deprecated in Java 10. You can [see the ticket](https://bugs.openjdk.java.net/browse/JDK-8194086) that completed the removal of this flag in Java 11. There needs to either be a new branch that supports Java 11, or it should be clearly marked that the CLI only supports Java 8-10. It would be nice if you could provide at the very least a Docker-based compiled version of the CLI that could be used so that Linux users aren't forced to install a bunch of dependencies that we won't be using for anything else but to build/run this tool. Makes Codacy less attractive to use.

**Comment by lolgab** [comment]
Hi @timnolte,
Thanks for letting us notice. Yes, the CLI should work on Java 11. I opened a PR to fix this: https://github.com/codacy/codacy-analysis-cli/pull/350
Anyway, we have already a Docker image of the CLI on docker hub https://github.com/codacy/codacy-analysis-cli/blob/master/README.md#docker
https://hub.docker.com/r/codacy/codacy-analysis-cli/tags

The documentation should be improved to make it more clear.

**Comment by timnolte** [comment]
@lolgab thanks for following up. I'm glad to see a Docker image available, I'll give that a try.

**Comment by franciscodua** [comment]
Hey @timnolte 
I'll close this issue. Feel free to re-open it or create a new one if the image doesn't work for you

**Comment by timnolte** [comment]
Are you updating your documentation to indicate that the CLI is only compatible with Java 8-10?

**Comment by lolgab** [comment]
> Are you updating your documentation to indicate that the CLI is only compatible with Java 8-10?

We merged #350 that removes the Java8 only flags.
