### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BigGan** [codacy/codacy-analysis-cli#400]

**Comment by franciscodua** [comment]
Hi @BigGan 
I noticed you opened several issues regarding different tools used to analyze different languages and I'll try to give you some tips on how to solve them (I hope).

In this specific issue, it seems you don't have a configuration file that ESLint can read, nor does it fetch the configuration from Codacy (you can use Codacy's configuration if you add your repository to Codacy and use a project token in the CLI).
And this also happens in some of the other issues you opened.

Is the repository you want to analyze open source? If so we can check it and give you a more detailed response.
And if not, what languages does that repository use? You can check [this](https://docs.codacy.com/getting-started/supported-languages-and-tools/) list to see what tools you should be using for your repository based on the languages you use there.

Finally, some of our tools are what we call client-side tools. The idea is that you run the tool on your side, and then send the results to Codacy. Therefore, you cannot run those tools directly in the CLI. Check the tools marked as Standalone [here](https://docs.codacy.com/related-tools/local-analysis/client-side-tools/#running-the-client-side-tools).

This answer pertains to:
#392 
#393 
#394 
#395 
#396 
#397 
#398 
#399 
#400
#401
#402
#403
