### ISSUE TITLE
[CY-4739] "--parallel 100" doesn't make execution parallel 

### ISSUE THREAD

**Issue by BigGan** [codacy/codacy-analysis-cli#406]
I found something wrong with the "--parallel" command. 

I used the two commands to analyze my code(--parallel 100 / --parallel 1):

```shell
sudo java -jar codacy-analysis-cli-assembly-6.3.0-featuresupportmetricinconfigfilecy3986.3.a42905d.jar analyze --format json --directory mycode --output myresult.json --parallel 100

sudo java -jar codacy-analysis-cli-assembly-6.3.0-featuresupportmetricinconfigfilecy3986.3.a42905d.jar analyze --format json --directory mycode --output myresult.json --parallel 1
```

I found the both codacy-analysis-cli call docker container of plugins one by one, not parallel. And they spent the same time.
so is there any wrong with "--parallel"? and how to fix it ?

thx ):

**Comment by lolgab** [comment]
Thank you @BigGan!
You are right, the execution is sequential and has not been working in parallel for years!
I'm fixing that in #407!
Good catch!

**Comment by BigGan** [comment]
> Thank you @BigGan!
> You are right, the execution is sequential and has not been working in parallel for years!
> I'm fixing that in #407!
> Good catch!

thx :)

**Comment by lolgab** [comment]
I'm reopening the issue until we merge the fix :)

**Comment by lolgab** [comment]
Version `7.0.0` is out with the fix
