### ISSUE TITLE
[CY-6627] CODACY_API_BASE_URL environment variable not picked up

### ISSUE THREAD

**Issue by jagadishrajr** [codacy/codacy-analysis-cli#456]
I am trying to use codacy-analysis-cli to execute Codacy code analysis locally. I have observed that CODACY_API_BASE_URL is not picked up while using the script or docker run methods. My requirement is to run the analysis for our enterprise version of codacy. I would like to know if this is an expected behaviour or did I miss any steps.

Docker run command that I used.

> docker run \
>   --rm=true \
>   --env CODACY_CODE="$CODACY_CODE" \
>   --env CODACY_API_BASE_URL="$CODACY_API_BASE_URL" \
>   --env CODACY_PROJECT_TOKEN="$CODACY_PROJECT_TOKEN" \
>   --volume /var/run/docker.sock:/var/run/docker.sock \
>   --volume "$CODACY_CODE":"$CODACY_CODE" \
>   --volume /tmp:/tmp \
>   codacy/codacy-analysis-cli:stable \
>     analyze --tool eslint --skip-ssl-verification --verbose
> 

CODACY_API_BASE_URL and CODACY_PROJECT_TOKEN are added as environment variables.

Execution logs:

> 11/17 08:08:23 INFO  c.c.a.c.c.Environment:74 - API base URL found in argument `--codacy-api-base-url` 
> 11/17 08:08:23 INFO  c.c.a.c.c.Environment:65 - Using API base URL https://api.codacy.com 
> 11/17 08:08:23 INFO  c.c.a.c.c.Environment:72 - Project token not passed through argument `--project-token` 
> 11/17 08:08:23 INFO  c.c.a.c.c.Environment:72 - API token not passed through argument `--api-token` 
> 11/17 08:08:23 INFO  c.c.a.c.c.Environment:74 - Project token found in environment variable `CODACY_PROJECT_TOKEN` 

I am not using _--codacy-api-base-url_ anywhere in my docker run command.

**Comment by DMarinhoCodacy** [comment]
Hello @jagadishrajr

If you want to run this in an on-prem Codacy instance, you need to use the URL of your current instance like "https://your-codacy-instance.com". Can you give it a try?

Kind regards,
David Marinho
