### ISSUE TITLE
[CY-6628] skip-ssl-verification not working as expected

### ISSUE THREAD

**Issue by jagadishrajr** [codacy/codacy-analysis-cli#457]
I am trying to execute analysis locally and upload the report later to our Codacy enterprise version server. I have followed the documentation and added the tag _--skip-ssl-verification_ to skip the SSL verification for my API url. 

Below is the command that I've used.

> % codacy-analysis-cli analyze \
>   --codacy-api-base-url https://codacy.mydomain.com \
>   --skip-ssl-verification \
>   --tool eslint \
>   --verbose

I can see from debug logs that I am able to successfully get the project analysis configuration from codacy remote server. 

> 11/17 08:29:09 INFO  c.c.a.c.clients.CodacyClient:161 - Success getting config file from endpoint "/project/analysis/configuration"  
> 11/17 08:29:09 INFO  c.c.a.c.clients.CodacyClient:168 - Success parsing remote configuration 
> 11/17 08:29:09 INFO  c.c.a.c.c.Environment:74 - Project directory found in environment variable `CODACY_CODE`

However, it does not pass when it tries to fetch the tools information. It fails with an SSL error.

> 11/17 08:29:20 ERROR c.c.a.c.command.AnalyseCommand:111 - Could not get tools due to: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by DMarinhoCodacy** [comment]
Hello @jagadishrajr 

Thanks for reporting this.

It seems you had some problems with the certificate in the Java Keystore on your computer. There are some articles on the internet to help you with that, like this one "https://blog.packagecloud.io/solve-pkix-path-building-failed/". 

Kind regards,
David Marinho
