### ISSUE TITLE
[TS-180] After updating cli to version 7.7.0 and 7.7.1 cli is not working as expected

### ISSUE THREAD

**Issue by puneetamb** [codacy/codacy-analysis-cli#464]
Whenever I try to execute any cli command, instead of executing the command it's showing usage guide in output. 
Steps to repro the issue:
- Try executing codacy-analysis-cli analyze. It prints usage guide instead of running analysis.
- Same happens if we try to execute codacy-analysis-cli -v to get the version.

Screenshot attached for reference:
 
<img width="628" alt="Screenshot 2023-01-20 at 7 49 47 PM" src="https://user-images.githubusercontent.com/64578137/213721204-0db6ca09-3736-4557-ba34-ebe2b12fe2f2.png">

It works fine after reverting back to 7.6.8

**Comment by stefanvacareanu7** [comment]
Hi there,

I have reverted the changes that caused this. The tool should work fine.

Thanks!
