### ISSUE TITLE
[TS-324] Upload codacy/codacy-analysis-cli image to Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by oak2** [codacy/codacy-analysis-cli#476]
It would be great to use Amazon ECR Public Gallery to pull the image because of the DockerHub pull limits.
Thanks.

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching our community!

I will pass your proposal internally.

Best,
Stefan

**Comment by oak2** [comment]
Still waiting for this.
